---
- name: Installer un package sur Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Apache
      apt:
        name: apache2
        state: present